AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudformation for vpc'
Resources: 
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '172.16.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC
